config/routes.rb
Rails.application.routes.draw do
  # get 'home/index'
  root 'home#index'

  get 'say/hello'

  get 'say/goodbye'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/say_controller.rb
class SayController < ApplicationController

  def hello
    @time = Time.now
    @files = Dir.glob('*')
  end

  def goodbye
    @time = Time.now
    @time_later = 1.hour.from_now.localtime
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/views/home/index.html.erb
<h1>Hello World!</h1>
This is the first of many pages!

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Grushenka</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/say/goodbye.html.erb
<h1>Goodbye from Rails..</h1>

<p>
  It was nice having you here.  Perhaps you may come back in an hour?  It's now <%= @time %>...
  so maybe later at  <%= @time_later %>?
</p>

<p>
  Time to say <%= link_to 'Hello', say_hello_path %>
</p>

app/views/say/hello.html.erb
<h1>Hello from Rails!</h1>

<p>
  It is now <%= @time %>.  1 & 2 is equal to <%= 1+2 %>.  If you join up "Cow" and "Boy" using rails, it looks like:
  <%= "Cow" + "Boy" %>.
</p>

<ul>
  <% for file in @files %>
    <li>file name is: <%= file %></li>
  <% end %>
</ul>

<p>
  Time to say <%= link_to 'Goodbye', say_goodbye_path %>
</p>


<!--app/views/say/hello.html.erb-->